spring:
    profiles:
        active: main
---
spring:
    profiles: main
server:
  port: 80

eureka:
  client:
    register-with-eureka: false #不向eureka注册自己
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/
      
---
spring:
    profiles: feign
server:
  port: 80

eureka:
  client:
    register-with-eureka: false #不向eureka注册自己
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/

feign:
  circuitbreaker:
    enabled: true
---
spring:
  profiles: hystrix
  application:
    name: eureka-consumer-feign-hystrix-dashboard
# 服务提供端口
server:
  port: 9001
# 注册到eureka服务端的地址
eureka:
  client:
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/ #,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/

  instance:
    instance-id: eureka-consumer-feign-hystrix-dashboard-9001
    prefer-ip-address: true



hystrix:
  dashboard:
    proxy-stream-allow-list:
      - "*"