spring:
    profiles:
        active: dev
        
---
spring:
    profiles: one
server:
  port: 7001


eureka:
  instance:
    hostname: jzh.eureka7001.com 
  client:
    register-with-eureka: false 
    fetch-registry: false 
    service-url:
      defaultZone: http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/
---
spring:
    profiles: two
server:
  port: 7002


eureka:
  instance:
    hostname: jzh.eureka7002.com 
  client:
    register-with-eureka: false 
    fetch-registry: false 
    service-url:
      defaultZone: http://jzh.eureka7003.com:7003/eureka/,http://jzh.eureka7001.com:7001/eureka/
---
spring:
    profiles: three
server:
  port: 7003


eureka:
  instance:
    hostname: jzh.eureka7003.com 
  client:
    register-with-eureka: false 
    fetch-registry: false 
    service-url:
      defaultZone: http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7001.com:7001/eureka/