server:
  port: 9753

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: http://localhost:8001         #匹配后提供服务的路由地址
          predicates:
            - Path=/dept/** #断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: http://localhost:80        #匹配后提供服务的路由地址
          predicates:
            - Path=/** #断言，路径相匹配的进行路由


eureka:
  client:
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway9753.com
    prefer-ip-address: true
