spring:
    profiles:
        active: dev
---
server:
  port: 9753

spring:
  profiles: dev
  cloud:
    gateway:
      routes:
        - id: payment_routh   
          uri: http://localhost:8001         
          predicates:
            - Path=/dept/** 
        - id: payment_routh2    
          uri: http://localhost:80       
          predicates:
            - Path=/** 


eureka:
  client:
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway9753.com
    prefer-ip-address: true
