spring:
    profiles:
        active: one

---
server:
  port: 8001


mybatis:
  type-aliases-package: com.jzh.springcloud.pojo

  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: one
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root



eureka:
  instance:
    instance-id: SpringCloud-provider-dept-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/

info:
  app.name: jzh_springcloud
  company.name: HUAWEi




management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 8002


mybatis:
  type-aliases-package: com.jzh.springcloud.pojo

  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: two
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

eureka:
  instance:
    instance-id: SpringCloud-provider-dept-8002
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/

info:
  app.name: jzh_springcloud
  company.name: HUAWEi

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---
server:
  port: 8003


mybatis:
  type-aliases-package: com.jzh.springcloud.pojo

  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: three
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root



eureka:
  instance:
    instance-id: SpringCloud-provider-dept-8003
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/

info:
  app.name: jzh_springcloud
  company.name: HUAWEi




management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---
server:
  port: 8001


mybatis:
  type-aliases-package: com.jzh.springcloud.pojo

  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: hystrix
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root



eureka:
  instance:
    instance-id: SpringCloud-provider-dept-hystrix-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://jzh.eureka7001.com:7001/eureka/,http://jzh.eureka7002.com:7002/eureka/,http://jzh.eureka7003.com:7003/eureka/

info:
  app.name: jzh_springcloud
  company.name: HUAWEi




management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
